### ISSUE TITLE
@import “breakpoint”; throws not found error

### ISSUE THREAD

**Issue by Snugug** [at-import/breakpoint#52]
(from http://stackoverflow.com/questions/17090191/import-breakpoint-throws-not-found-error/17090653?noredirect=1#comment24723128_17090653)

I was working on this project yesterday using Sass and Breakpoint and everything was fine. This morning however when I went to compile using `sass --watch` .. I am getting this error:

```
error ../sass/screen.scss (Line 6: File to import not found or unreadable: breakpoint. Load path: /Users/MOD3/Sites/GABE/stylesheets/stylesheets)
```

**Comment by ryanjbonnell** [comment]
I was having the same issue when using Breakpoints Sass installed via Bower following the  [Breakpoint Wiki installation instructions][1].

The error message I was getting was the following:

```
error scss/style.scss (Line 1: File to import not found or unreadable: breakpoint.
Load path: ~Sites/example.dev/scss)
```
The Wiki documentation said to install Breakpoints via Bower and include Breakpoints as an include:

> **Install Breakpoints**
> 
> `$ bower install breakpoint-sass --save-dev`
> 
> **Import Breakpoints Sass (e.g. scss/style.scss)**
> 
> `@import "breakpoint";`

The Wiki doesn't provide much information for troubleshooting, but the solution was to include Breakpoints Sass from the `_bower_components` directory in your Sass file:

`@import "../bower_components/breakpoint-sass/stylesheets/_breakpoint.scss";`

For anyone experiencing this problem, **the fix was to change the import / include path to point Sass to where the Breakpoints Sass files were located at.**

Kudos to Piotr Sikora for writing a helpful tutorial and documenting his workflow on using [Breakpoints Sass with Bower and Gulp][3].

[1]: https://github.com/at-import/breakpoint/wiki/Installation#requirements
[2]: http://sass-lang.com/guide#topic-5
[3]: http://fedojo.com/breakpoint-sass-configuration-and-how-to-use-it-gulp-js-include-paths/
