### ISSUE TITLE
aspect ratios syntax?

### ISSUE THREAD

**Issue by gavinengel** [at-import/breakpoint#76]
How can I test for aspect ratios with Breakpoint?

**Comment by joernroeder** [comment]
Hey @Snugug,
 i'm currently trying to restrict a set of styles to a specific range of screen aspect-ratio and found this issue just before i was going to open a question on stack overflow. I have a similar use case but instead of using `min-aspect-ratio` i tried the [Media Query Pairs](https://github.com/at-import/breakpoint/wiki/Advanced-Media-Queries#media-query-pairs) approach as described in the docs.

Following the docs something like `$aspect-pair: aspect-ratio 1/1 16/9;` should work – but it didn't as i'm running in the same issue as described in #169. Also using two strings as values `$aspect-pair: aspect-ratio  '1/1' '16/9';` doesn't work an throws an parser error.

```
>> Error: index out of bounds for `nth($list, $n)`
>>         on line 32 of node_modules/breakpoint-sass/stylesheets/breakpoint/parsers/_triple.scss
>> >> triple-default($string, nth($numbers, 1), nth($numbers, 2));
```
Is it worth reopening the issue until there is a solution for a pair of strings?
thanks in advance!
